name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    timeout-minutes: 15  # ⏳ 실행 시간 확보
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle (Skip Tests)
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/libs/boardparadice-0.0.4-SNAPSHOT.jar"
          target: "/home/ubuntu/"
          strip_components: 2

      - name: Restart Application on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Stopping existing application..."
            sudo systemctl stop deploy_app || echo "No process found"

            echo "Starting new application..."
            sudo systemctl daemon-reload
            sudo systemctl restart deploy_app  # ✅ systemd를 사용하여 실행
            sleep 5  # ✅ 애플리케이션이 시작될 시간을 줌

            echo "Checking running processes..."
            sudo systemctl status deploy_app  # ✅ 실행 상태 확인

            echo "Checking logs..."
            tail -n 50 /home/ubuntu/app.log || echo "Log file not found"
            
