name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    timeout-minutes: 15  # ⏳ 실행 시간 확보
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle (Skip Tests)
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/libs/boardparadice-0.0.4-SNAPSHOT.jar"
          target: "/home/ubuntu/"
          strip_components: 2
          overwrite: true

      - name: Restart Application on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Stopping existing application..."
            sudo systemctl stop deploy_app || echo "No process found"

            echo "Reloading systemd daemon..."
            sudo systemctl daemon-reload

            echo "Starting new application..."
            sudo systemctl start deploy_app

            sleep 5

            echo "Checking service status..."
            sudo systemctl status deploy_app

            echo "Checking logs..."
            sudo journalctl -u deploy_app -n 50 --no-pager || echo "Log file not found"
