name: Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    timeout-minutes: 15  # ⏳ 실행 시간 확보
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle (Skip Tests)
        run: ./gradlew clean build -x test  # 테스트 제외하고 빌드

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "build/libs/boardparadice-0.0.4-SNAPSHOT.jar"
          target: "/home/ubuntu/"
          strip_components: 2
          overwrite: true

      - name: Restart Application on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Stopping existing application..."
            pkill -f boardparadice-0.0.4-SNAPSHOT.jar || echo "No process found"

            echo "Starting new application..."
            nohup java -jar /home/ubuntu/boardparadice-0.0.4-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 < /dev/null &
            disown
            sleep 5

            echo "Checking running processes..."
            pgrep -fl boardparadice-0.0.4-SNAPSHOT.jar

            echo "Checking logs..."
            tail -n 50 /home/ubuntu/app.log || echo "Log file not found"

            # 강제로 정상 종료(0) 코드를 반환
            exit 0